const data = [
  {"id":1,"question":"What does HTTPS provide?","answers":["Encrypted secure communication","Faster internet speed","Better website design","Free hosting"],"correct":0,"credit":2},
  {"id":2,"question":"Which one is a hashing algorithm?","answers":["AES","RSA","SHA-256","DES"],"correct":2,"credit":3},
  {"id":3,"question":"What is the strongest password?","answers":["1234","admin","1234admin","1234#@$$admIN"],"correct":3,"credit":2},
  {"id":4,"question":"What does a firewall do?","answers":["Encrypt passwords","Filter network traffic","Increase battery life","Store data"],"correct":1,"credit":2},
  {"id":5,"question":"Which is an example of malware?","answers":["Firewall","Antivirus","Trojan","Router"],"correct":2,"credit":2},
  {"id":6,"question":"What is phishing?","answers":["A hacking technique using fake messages","A type of encryption","A strong password","A network router"],"correct":0,"credit":2},
  {"id":7,"question":"Which of these is private information?","answers":["Favorite color","Public email","Home password","Nickname"],"correct":2,"credit":2},
  {"id":8,"question":"What does 2FA stand for?","answers":["Two-Factor Authentication","Two-Firewall Access","Fast Authentication","Full Admin Access"],"correct":0,"credit":2},
  {"id":9,"question":"Which one is a secure practice?","answers":["Sharing passwords","Using one password everywhere","Using long random passwords","Saving passwords on paper"],"correct":2,"credit":2},
  {"id":10,"question":"What does a VPN do?","answers":["Hides your IP address","Makes internet free","Deletes viruses","Improves graphics"],"correct":0,"credit":2},
  {"id":11,"question":"Which one is a strong password pattern?","answers":["Name123","Password1","Qwerty!","hT9@!gL920$"],"correct":3,"credit":3},
  {"id":12,"question":"Which one is a type of social engineering?","answers":["AES","Phishing","VPN","Firewall"],"correct":1,"credit":3},
  {"id":13,"question":"What is a brute-force attack?","answers":["Guessing every possible password","Blocking websites","Encrypting files","Resetting the router"],"correct":0,"credit":3},
  {"id":14,"question":"Which device can use biometric authentication?","answers":["Keyboard","Mouse","Fingerprint scanner","Speaker"],"correct":2,"credit":2},
  {"id":15,"question":"A strong password should contain:","answers":["Only numbers","Letters + numbers + symbols","Only your name","Only lowercase letters"],"correct":1,"credit":2},
  {"id":16,"question":"What does RSA use to encrypt data?","answers":["Symmetric keys","Asymmetric (public/private) keys","Hashing only","Quantum keys"],"correct":1,"credit":3},
  {"id":17,"question":"Which one is a symmetric encryption algorithm?","answers":["RSA","AES","ECC","SHA-1"],"correct":1,"credit":3},
  {"id":18,"question":"What is an example of a hash function?","answers":["SHA-256","RSA","AES","TLS"],"correct":0,"credit":3},
  {"id":19,"question":"What is SQL Injection?","answers":["Injecting encrypted data","Manipulating database queries","Breaking the firewall","Blocking ports"],"correct":1,"credit":5},
  {"id":20,"question":"Which protocol secures Wi-Fi?","answers":["WPA3","FTP","HTTP","SMTP"],"correct":0,"credit":3},
  {"id":21,"question":"What does a digital signature provide?","answers":["Deletion of data","Identity verification","Free storage","Faster downloads"],"correct":1,"credit":3},
  {"id":22,"question":"Which is an example of two-factor authentication?","answers":["Password + OTP code","Password only","Fingerprint only","Username + password"],"correct":0,"credit":2},
  {"id":23,"question":"What is the main purpose of encryption?","answers":["Speed","Compression","Privacy & confidentiality","Saving money"],"correct":2,"credit":2},
  {"id":24,"question":"Which one is a password manager?","answers":["Chrome","1Password","YouTube","Outlook"],"correct":1,"credit":2},
  {"id":25,"question":"What does a DDoS attack do?","answers":["Encrypts files","Floods a server with traffic","Creates fake emails","Fixes network issues"],"correct":1,"credit":3},
  {"id":26,"question":"What is the safest way to store passwords?","answers":["Text file on desktop","Password manager","Screenshot","Notebook"],"correct":1,"credit":2},
  {"id":27,"question":"Which port is used for HTTPS?","answers":["80","443","21","25"],"correct":1,"credit":2},
  {"id":28,"question":"A strong encryption key should be:","answers":["Short","Predictable","Random and long","Based on birthdays"],"correct":2,"credit":3},
  {"id":29,"question":"Which of these is a cyber attack?","answers":["AES","Phishing","SQL","HTML"],"correct":1,"credit":3},
  {"id":30,"question":"Which factor is biometric?","answers":["Password","Keycard","Fingerprint","PIN code"],"correct":2,"credit":2},
  {"id":31,"question":"What does hashing NOT allow?","answers":["Reversing to original data","Storing passwords securely","Checking integrity","Generating fixed-size output"],"correct":0,"credit":3},
  {"id":32,"question":"Which of these is unsafe behavior?","answers":["Using 2FA","Using the same password everywhere","Updating software","Using antivirus"],"correct":1,"credit":2},
  {"id":33,"question":"What is ransomware?","answers":["A program that locks your files","A type of Wi-Fi","A VPN service","A password generator"],"correct":0,"credit":3},
  {"id":34,"question":"Which is used for password hashing?","answers":["bcrypt","AES","RSA","TLS"],"correct":0,"credit":3},
  {"id":35,"question":"What does the Diffie-Hellman algorithm enable?","answers":["Key exchange","Data compression","Fingerprint scanning","IP masking"],"correct":0,"credit":3},
  {"id":36,"question":"What type of attack is 'man-in-the-middle'?","answers":["Intercepting communication","Flooding a server","Guessing passwords","Deleting files"],"correct":0,"credit":3},
  {"id":37,"question":"Which cryptographic method uses elliptic curves?","answers":["DES","ECC","MD5","TLS 1.0"],"correct":1,"credit":3},
  {"id":38,"question":"Which hashing algorithm is considered broken?","answers":["SHA-256","SHA-3","MD5","BLAKE2"],"correct":2,"credit":3},
  {"id":39,"question":"What does salting a password help prevent?","answers":["Stronger Wi-Fi signal","Rainbow table attacks","Faster boot speed","Lower bandwidth"],"correct":1,"credit":3},
  {"id":40,"question":"AES operates on blocks of:","answers":["32 bits","64 bits","128 bits","512 bits"],"correct":2,"credit":3},
  {"id":41,"question":"What is the purpose of hashing in digital signatures?","answers":["To compress the data","To verify integrity","To encrypt messages","To delete metadata"],"correct":1,"credit":3},
  {"id":42,"question":"Which cryptography relies on factoring large prime numbers?","answers":["AES","RSA","SHA-1","MD5"],"correct":1,"credit":3},
  {"id":43,"question":"Which protocol replaced SSL?","answers":["TLS","FTP","SSH","DNS"],"correct":0,"credit":3},
  {"id":44,"question":"What is a zero-day vulnerability?","answers":["A bug unknown to vendors","A firewall feature","A password type","A hash collision"],"correct":0,"credit":5},
  {"id":45,"question":"In cybersecurity, CIA stands for:","answers":["Central Intelligence Agency","Confidentiality, Integrity, Availability","Crypto Internet Access","Control Integrity Authentication"],"correct":1,"credit":3},
  {"id":46,"question":"What is a 'rainbow table' used for?","answers":["Cracking hashed passwords","Encrypting data","Filtering networks","Building VPN tunnels"],"correct":0,"credit":3},
  {"id":47,"question":"What is the biggest threat to passwords?","answers":["Length","Human behavior","Computers","Routers"],"correct":1,"credit":2},
  {"id":48,"question":"Which cryptographic system is quantum-resistant?","answers":["RSA","AES-128","SHA-1","Lattice-based crypto"],"correct":3,"credit":5},
  {"id":49,"question":"What is the recommended minimum length for strong passwords?","answers":["6 characters","8 characters","12+ characters","100 characters"],"correct":2,"credit":2},
  {"id":50,"question":"Which one is a digital certificate?","answers":["An encrypted file","A signed document verifying identity","A password manager","A VPN connection"],"correct":1,"credit":3}
]

export default data;
