import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "404",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { 
  return (
    <html lang="en">
            <head>
        {/* <link rel="icon" href="/image.png" sizes="any" /> */}
        {/* Or PNG */}
        <link rel="icon" href="/image.png" type="image/png" />
      </head>


      

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  red`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
